# Generated by Django 2.0.2 on 2018-09-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=180)),
                ('Apellido_paterno', models.CharField(max_length=90)),
                ('Apellido_materno', models.CharField(max_length=90)),
                ('Correo', models.EmailField(max_length=254)),
            ],
        ),
    ]
