# Generated by Django 2.1.1 on 2018-09-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contactos registrados por medio del formulario'},
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Apellido_materno',
            field=models.CharField(max_length=90, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Apellido_paterno',
            field=models.CharField(max_length=90, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Nombre',
            field=models.CharField(max_length=180, verbose_name='Nombre'),
        ),
    ]
