# Generated by Django 2.0.2 on 2018-10-30 05:32

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto',
            options={'verbose_name': 'Contactos registrados por medio del formulario'},
        ),
        migrations.AddField(
            model_name='contacto',
            name='calle',
            field=models.CharField(default='Calle', max_length=90, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='cod_postal',
            field=models.CharField(default='H1W 3J3', max_length=90, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='colonia',
            field=models.CharField(default='colonia', max_length=90, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='estados',
            field=models.CharField(default='Estados', max_length=90, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='contacto',
            name='municipio',
            field=models.CharField(default='municipio', max_length=90, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='no_exterior',
            field=models.CharField(default='Numero exterior', max_length=90, verbose_name='Numero exterior'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='no_interior',
            field=models.CharField(default='Numero interior', max_length=90, verbose_name='Numero interior'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nom_negocio',
            field=models.CharField(default='lol', max_length=90, verbose_name='Nombre del negocio'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El numero de telefono debe ser ingresado de la siguiente manera: '+999999999'. Máximo 15 digitos son aceptados.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Apellido_materno',
            field=models.CharField(max_length=90, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Apellido_paterno',
            field=models.CharField(max_length=90, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Correo',
            field=models.EmailField(max_length=254, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='Nombre',
            field=models.CharField(max_length=180, verbose_name='Nombre'),
        ),
    ]
