# Generated by Django 2.0.2 on 2018-10-29 01:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contacto_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='cod_postal',
            field=models.CharField(default='H1W 3J3', max_length=90, verbose_name='Código postal'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='colonia',
            field=models.CharField(default='colonia', max_length=90, verbose_name='Colonia'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='estados',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja_California', 'Baja California'), ('Baja_California_sur', 'Baja California Sur'), ('Campeche', 'Campeche')], default='Aguascalientes', max_length=20),
        ),
        migrations.AddField(
            model_name='contacto',
            name='municipio',
            field=models.CharField(default='municipio', max_length=90, verbose_name='Municipio'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='nom_negocio',
            field=models.CharField(default='lol', max_length=90, verbose_name='Nombre del negocio'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="El numero de telefono debe ser ingresado de la siguiente manera: '+999999999'. Máximo 15 digitos son aceptados.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
