# Generated by Django 2.0.2 on 2018-10-30 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181029_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='estados',
        ),
    ]
