# Generated by Django 2.0.2 on 2018-10-30 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_contacto_estados'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='calle',
            field=models.CharField(default='Unknown', max_length=90, verbose_name='Calle'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='estados',
            field=models.CharField(default='Quebec', max_length=90, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='no_exterior',
            field=models.CharField(default='Unknown', max_length=90, verbose_name='Numero exterior'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='no_interior',
            field=models.CharField(default='Unknown', max_length=90, verbose_name='Numero interior'),
        ),
    ]
