# Generated by Django 2.0.2 on 2018-10-30 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20181030_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='fecha',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='calle',
            field=models.CharField(default='Calle', max_length=90, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='estados',
            field=models.CharField(default='Estados', max_length=90, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='no_exterior',
            field=models.CharField(default='Numero exterior', max_length=90, verbose_name='Numero exterior'),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='no_interior',
            field=models.CharField(default='Numero interior', max_length=90, verbose_name='Numero interior'),
        ),
    ]
